### ISSUE TITLE
Is it possible to disable PGP verification of files?

### ISSUE THREAD

**Issue by bodsch** [edlanglois/pkgbuild-action#11]
I am currently trying to integrate a build, but keep failing with this error message: "FAILED (unknown public key C6E319C334410682)".

I have tried to configure the job via the environment variable `INPUT_MAKEPKGARGS`, but unfortunately this does not have the desired result.
My current workflow is here:
https://github.com/bodsch/aur-icingadb/blob/main/.github/workflows/main.yml

**Comment by RiverOnVenus** [comment]
Hi, maybe this can skip the PGP verification.

```
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          makepkgArgs: "--skippgpcheck"
```

It works fine in my workflow.

![image](https://user-images.githubusercontent.com/79885139/196015605-a7ef71b1-813d-4a8a-ba69-5cadfc9af235.png)

And my current workflow is here:
[https://github.com/RiverOnVenus/linux-ck-tt/blob/master/.github/workflows/build.yml](https://github.com/RiverOnVenus/linux-ck-tt/blob/master/.github/workflows/build.yml)
