### ISSUE TITLE
Error entrypoint.sh

### ISSUE THREAD

**Issue by Squitch1** [edlanglois/pkgbuild-action#6]
Hello, i have an issue while running your action :
```
chmod: changing permissions of '/github/workspace/src': Operation not permitted
==> ERROR: An unknown error has occurred. Exiting...
/entrypoint.sh: line 59:   909 User defined signal 1   sudo -H -u builder makepkg --syncdeps --noconfirm ${INPUT_MAKEPKGARGS:-}
```
That is my action script :
```
jobs:  
  pkgbuild:    
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout      
        uses: actions/checkout@v2    
      - name: Makepkg     
        id: makepkg      
        uses: edlanglois/pkgbuild-action@v1.1.6    
      - name: Print Package Files      
        run: |        
          echo "Successfully created the following package archive"        
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"    
      - name: Upload Package Archive      
        uses: actions/upload-artifact@v2     
        with:        
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
```
